create table if not exists audits (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  total_monthly_savings numeric not null,
  total_annual_savings numeric not null,
  result_json jsonb not null,
  created_at timestamptz default now()
);

create table if not exists leads (
  id bigint generated by default as identity primary key,
  email text not null,
  company text,
  role text,
  audit_id text,
  created_at timestamptz default now()
);
